#!/bin/bash
# NOTE: bash is required due to an obscure problem with dash, quote expansion and variables with spaces
#       Detected with expansion of 'Domain Users' group (a really brain-damaged choice for a group name)

# -------
# File:        aurex-lpadmin
# Description: manage papercut printers
# Author:      Luis Antonio Garcia Gisbert <luisgg@gmail.com> 
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along 
# with this program; if not, write to the Free Software Foundation, Inc., 
# 51 Franklin St, Fifth Floor, Boston MA 02110-1301 USA
# --------

# funcs
# -----

die(){
	echo "$1" >&2
	exit 1
}

usage(){
	die "Usage: $(basename "$0") [--force]  {update|remove}"
}

remove_printer(){
	lpadmin -x "$1" || true
	rm -f "$DB_DIR/$1"
}


if [ "$1" = "--force" ] ; then
	FORCE="Y"
	shift
fi
DB_DIR="/var/lib/aurex-lpadmin"
PRINTERS_DIR="/etc/aurex-lpadmin/printers.d"
DEFAULT_PRINTER="/etc/aurex-lpadmin/default"
OLD_DEFAULT_PRINTER="/etc/aurex-lpadmin/old-default"

case "$1" in
	update)
		pidof cupsd >/dev/null || exit 0
		for f in $(ls -1 $DB_DIR) ; do
			[ -e "$PRINTERS_DIR/$f" ] || remove_printer "$f"
		done
		for f in $(ls -1 $PRINTERS_DIR) ; do
			if [ "$FORCE" ] || [ ! -e "$DB_DIR/$f" ] ; then
				[ ! -e "$DB_DIR/$f" ] || remove_printer "$f"
				# reset variables
				PRINTER_PPD=""
				PRINTER_URI=""
				PRINTER_ALLOW=""
		
				# TODO: parse printer info
				. "$PRINTERS_DIR/$f"
				if [ "$PRINTER_PPD" ] && [ "$PRINTER_URI" ] ; then
					if lpadmin -p "$f" -E -v "$PRINTER_URI" -m "$PRINTER_PPD" ; then
						cp $PRINTERS_DIR/$f $DB_DIR/
						# getent group "$kk" |cut -f 3 -d :
						[ -z "$PRINTER_ALLOW" ] || lpadmin -p "$f" -u allow:"$PRINTER_ALLOW" || true
					fi
				fi
			fi
		done
		# test if DEFAULT_PRINTER is a no-broken link and if it has been changed
		if [ -L "$DEFAULT_PRINTER" ] &&  [ -r "$DEFAULT_PRINTER" ] ; then
			DEF_PRINTER="$(basename "$(readlink -f "$DEFAULT_PRINTER")")"
			if [ -L "$OLD_DEFAULT_PRINTER" ] ; then
				OLD_PRINTER="$(basename "$(readlink -f "$OLD_DEFAULT_PRINTER")")"
			fi
			if [ "$DEF_PRINTER" != "$OLD_PRINTER" ] ; then
				rm -f "$OLD_DEFAULT_PRINTER"
				ln -s "$(readlink -f "$DEFAULT_PRINTER")" "$OLD_DEFAULT_PRINTER" || true
				lpadmin -d "$DEF_PRINTER" || true
			fi
		fi
		;;
	remove)
		pidof cupsd >/dev/null || exit 0
		for f in $(ls -1 $DB_DIR) ; do
			remove_printer "$f"
		done
		;;
	*)
		usage
		;;
esac
exit 0

