#!/bin/sh
#
# The environment variables passed by pam-script onto the script
# (all will exist but some may be null if not applicable):
#	PAM_SERVICE	- the application that's invoking the PAM stack
#	PAM_TYPE	- the module-type (e.g. auth,account,session,password)
#	PAM_USER	- the user being authenticated into
#	PAM_RUSER	- the remote user, the user invoking the application
#	PAM_RHOST	- remote host
#	PAM_TTY		- the controlling tty
#	PAM_AUTHTOK	- password in readable text
#
#echo $stamp $script $PAM_SERVICE $PAM_TYPE				\
#	user=$PAM_USER ruser=$PAM_RUSER rhost=$PAM_RHOST		\
#	tty=$PAM_TTY							\
#	args=["$@"]							\
#	>> $LOGFILE
#chmod 666 $LOGFILE > /dev/null 2>&1


is_network_user(){
	PASS_USER="$1"
	NUM_USERS=$(getent passwd "$PASS_USER" |wc -l)
	[ $NUM_USERS -gt 0 ] || return 1
	NUM_LOCAL_USERS=$(grep "^$PASS_USER:" /etc/passwd |wc -l)
	[ $NUM_LOCAL_USERS -lt $NUM_USERS ] || return 1
	return 0
}

do_link(){
	if [ -h "$2" ] && [ "$(readlink "$2")" = "$1" ] ; then
		return 0
	fi
	
	rm -f "$2"
	ln -s "$1" "$2"
	chown -h $PAM_USER:$PGRID "$2"
}

do_link_prof(){
	do_link "/datos/.profesores/$PAM_USER" "$1"
}
do_link_pas(){
	do_link "/datos/.pas/$PAM_USER" "$1"

}
do_link_dep(){
	do_link "/datos/departamentos" "$1"
}

do_link_pub(){
	do_link "/datos/publico" "$1"
}

do_link_dir(){
	do_link "/datos/.direccion" "$1"
}

do_link_jef(){
	do_link "/datos/.jefatura" "$1"
}

do_link_pdf(){
	do_link "/datos/.pdf2conserjeria" "$1"
}

# mdm reports itslef as service nx ¿?
VALID_SERVICES_LIST="lightdm mdm nx"
VALID_TYPES_LIST="session"

TEACHERS_ID="501"
STUDENTS_ID="502"
SECRETAR_ID="503"
CONSERJE_ID="504"

MOUNT_TYPE="net"
#MOUNT_TYPE="glfs"

if [ -z "$PAM_SERVICE" ] || [ -z "$PAM_TYPE" ] || [ -z "$PAM_USER" ] || ! is_network_user "$PAM_USER" ; then
	exit 0
fi

if echo " $VALID_SERVICES_LIST " |grep -q " $PAM_SERVICE " && echo " $VALID_TYPES_LIST " |grep -q " $PAM_TYPE " ; then
	HDIR="$(getent passwd $PAM_USER |cut -f 6 -d :)"
	GLIST="$(groups $PAM_USER |cut -d : -f 2 |tr "[:lower:]" "[:upper:]")"
	PGRID="$(getent passwd $PAM_USER |cut -f 4 -d :)"
	DOC_LINK="$HDIR/MisDocumentos_Servidor"
	DEP_LINK="$HDIR/Departamentos"
	PUB_LINK="$HDIR/Publico_Servidor"

	DIR_LINK="$HDIR/Direccion"
	JEF_LINK="$HDIR/Jefatura"
	PDF_LINK="$HDIR/PDF-imprimir"

	do_link_dep "$DEP_LINK" 
	do_link_pub "$PUB_LINK" 

	case "$PGRID" in
		501)
			# PROFESORES
			do_link_prof "$DOC_LINK" 
			;;
		503)
			# SECRETARIA
			do_link_pas "$DOC_LINK" 
			;;

		504)
			# CONSERJERIA
			do_link_pas "$DOC_LINK" 
			do_link_pdf "$PDF_LINK" 
			;;
	esac
	if echo " $GLIST " |grep -q " PR_DIRECCION " ; then
		do_link_dir "$DIR_LINK" 
	fi
	if echo " $GLIST " |grep -q " PR_JEFATURA " ; then
		do_link_jef "$JEF_LINK" 
	fi
fi	
exit 0
