#!/bin/sh
#
# The environment variables passed by pam-script onto the script
# (all will exist but some may be null if not applicable):
#	PAM_SERVICE	- the application that's invoking the PAM stack
#	PAM_TYPE	- the module-type (e.g. auth,account,session,password)
#	PAM_USER	- the user being authenticated into
#	PAM_RUSER	- the remote user, the user invoking the application
#	PAM_RHOST	- remote host
#	PAM_TTY		- the controlling tty
#	PAM_AUTHTOK	- password in readable text
#
#echo $stamp $script $PAM_SERVICE $PAM_TYPE				\
#	user=$PAM_USER ruser=$PAM_RUSER rhost=$PAM_RHOST		\
#	tty=$PAM_TTY							\
#	args=["$@"]							\
#	>> $LOGFILE
#chmod 666 $LOGFILE > /dev/null 2>&1

is_network_user(){
	PASS_USER="$1"
	NUM_USERS=$(getent passwd "$PASS_USER" |wc -l)
	[ $NUM_USERS -gt 0 ] || return 1
	NUM_LOCAL_USERS=$(grep "^$PASS_USER:" /etc/passwd |wc -l)
	[ $NUM_LOCAL_USERS -lt $NUM_USERS ] || return 1
	return 0
}


VALID_SERVICES_LIST="lightdm"
VALID_TYPES_LIST="session"

exit 0
