#!/bin/sh
#OLD_TARGET_DIR="/clickcontrol"
TARGET_DIR="/var/lib/papercut-client"

usage(){
	echo "Usage: $(basename "$0") [install|remove|enable|disable]"
}

do_enable(){
	if [ -d "$TARGET_DIR" ] && [ -x "$TARGET_DIR/pc-client-linux.sh" ] && [ -d "$TARGET_DIR/lib" ] ; then
		sed -e "s%_@_TARGET_DIR_@_%$TARGET_DIR%g" /usr/share/ausias-papercut-client/papercut-client.sh.in > /etc/profile.d/papercut-client.sh
		chmod 755 "/etc/profile.d/papercut-client.sh"
	fi
}

do_disable(){
	rm -f /etc/profile.d/papercut-client.sh
}

case "$1" in 
	disable)
		do_disable
		;;
	enable)
		do_enable
		;;
	install)
		PCCLIENT_SHARE="//xwarrior/pcclient"
		TMP_DIR="$(mktemp -d)"
		CLIENT_DIR="$TMP_DIR/linux"
		# try to mount pcclient resource
		echo "Trying to mount $PCCLIENT_SHARE to get linux papercut client files"
		rc=0
		mount -t cifs "$PCCLIENT_SHARE" "$TMP_DIR" -o guest || rc=$?
		# do some additional tests
		if [ $rc -eq 0 ] && [ -d "$CLIENT_DIR" ] && [ -e "$CLIENT_DIR/pc-client-linux.sh" ] && [ -d "$CLIENT_DIR/lib" ] ; then
			mkdir -p "$TARGET_DIR"
			# bypass broken link ...
			cp -r $CLIENT_DIR/* $TARGET_DIR || true
			chmod 755 "$TARGET_DIR/pc-client-linux.sh"
			do_enable
			umount "$TMP_DIR" || true
			rmdir "$TMP_DIR" || true
			echo "Papercut client successfully installed"
		else
			umount "$TMP_DIR" || true
			rmdir "$TMP_DIR" || true
			echo "Error accessing $PCCLIENT_SHARE as guest" >&2
			echo "Papercut client NOT INSTALLED" >&2
		fi
		;;
	remove)
		rm -f /etc/profile.d/papercut-client.sh
		rm -fr "$TARGET_DIR"
		;;
	*)
		usage
		;;
esac

exit 0
