#!/bin/sh

TARGET_IFACE="eth0"
ALIAS_NUM="99"
ALIAS_ADDR="192.168.99"
ALIAS_MASK="255.255.255.0"


# verify interface
[ "$IFACE" = "$TARGET_IFACE" ] || exit 0
if [ "$MODE" = "start" ] ; then
	ifconfig $TARGET_IFACE:$ALIAS_NUM $ALIAS_ADDR.10 netmask $ALIAS_MASK || true
else
	ifconfig $TARGET_IFACE:$ALIAS_NUM down || true
fi

exit 0

